theme: jekyll-theme-slate
title: Survival and Flourishing<br>.Fund
baseurl: "" # the subpath of your site, e.g. /blog
url: "//survivalandflourishing.fund" # the base hostname & protocol for your site

github:
  is_project_page: false
